package com.portal.journey.entity;

import java.sql.Timestamp;
import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedTimestamp;

import lombok.Data;

@Data
@DynamoDBTable(tableName = "journey")
public class Journey {
	
	/**
	 * id
	 */
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	
	/**
	 * passengerId
	 */
	@DynamoDBAttribute
	private String passengerId;
	
	/**
	 * originLocation
	 */
	@DynamoDBAttribute
	private String originLocation;
	
	/**
	 * destinationLocation
	 */
	@DynamoDBAttribute
	private String destinationLocation;
	
	/**
	 * departureTime
	 */
	@DynamoDBAttribute
	private Timestamp departureTime;
	
	/**
	 * bestOptionRoute
	 */
	@DynamoDBAttribute
	private String bestOptionRoute;
	
	/**
	 * durationTime
	 */
	@DynamoDBAttribute
	private Long durationTime;
	
	/**
	 * journey date
	 */
	@DynamoDBAttribute
	private Date journeyDate;
	
	/**
	 * createdDateTime
	 */
	@DynamoDBAttribute
	private Date createdDateTime;
	
	/**
	 * updatedDateTime
	 */
	@DynamoDBAttribute
	private Date updatedDateTime;
	
	/**
	 * createdBy
	 */
	@DynamoDBAttribute
	private String createdBy;
	
	/**
	 * updatedBy
	 */
	@DynamoDBAttribute
	private String updatedBy;
	
	public Journey() {
		// TODO Auto-generated constructor stub
	}

	/**
	 * 
	 * @return
	 */
	public String getId() {
		return id;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * 
	 * @return
	 */
	public String getPassengerId() {
		return passengerId;
	}

	/**
	 * 
	 * @param passengerId
	 */
	public void setPassengerId(String passengerId) {
		this.passengerId = passengerId;
	}

	/**
	 * 
	 * @return
	 */
	public String getOriginLocation() {
		return originLocation;
	}

	/**
	 * 
	 * @param originLocation
	 */
	public void setOriginLocation(String originLocation) {
		this.originLocation = originLocation;
	}

	/**
	 * 
	 * @return
	 */
	public String getDestinationLocation() {
		return destinationLocation;
	}

	/**
	 * 
	 * @param destinationLocation
	 */
	public void setDestinationLocation(String destinationLocation) {
		this.destinationLocation = destinationLocation;
	}

	/**
	 * 
	 * @return
	 */
	public Timestamp getDepartureTime() {
		return departureTime;
	}

	/**
	 * 
	 * @param departureTime
	 */
	public void setDepartureTime(Timestamp departureTime) {
		this.departureTime = departureTime;
	}

	/**
	 * 
	 * @return
	 */
	public String getBestOptionRoute() {
		return bestOptionRoute;
	}

	/**
	 * 
	 * @param bestOptionRoute
	 */
	public void setBestOptionRoute(String bestOptionRoute) {
		this.bestOptionRoute = bestOptionRoute;
	}

	/**
	 * 
	 * @return
	 */
	public Long getDurationTime() {
		return durationTime;
	}

	/**
	 * 
	 * @param durationTime
	 */
	public void setDurationTime(Long durationTime) {
		this.durationTime = durationTime;
	}

	/**
	 * 
	 * @return
	 */
	public String getCreatedBy() {
		return createdBy;
	}

	/**
	 * 
	 * @param createdBy
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * 
	 * @return
	 */
	public String getUpdatedBy() {
		return updatedBy;
	}

	/**
	 * 
	 * @param updatedBy
	 */
	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	/**
	 * 
	 * @return
	 */
	@DynamoDBTypeConvertedTimestamp(pattern="yyyyMMddHHmmssSSS", timeZone="UTC")
	public Date getCreatedDateTime() {
		return createdDateTime;
	}

	/**
	 * 
	 * @param createdDateTime
	 */
	public void setCreatedDateTime(Date createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

	/**
	 * 
	 * @return
	 */
	@DynamoDBTypeConvertedTimestamp(pattern="yyyyMMddHHmmssSSS", timeZone="UTC")
	public Date getUpdatedDateTime() {
		return updatedDateTime;
	}

	/**
	 * 
	 * @param updatedDateTime
	 */
	public void setUpdatedDateTime(Date updatedDateTime) {
		this.updatedDateTime = updatedDateTime;
	}

	/**
	 * 
	 * @return
	 */
	@DynamoDBTypeConvertedTimestamp(pattern="yyyy-MM-dd")
	public Date getJourneyDate() {
		return journeyDate;
	}

	/**
	 * 
	 * @param journeyDate
	 */
	public void setJourneyDate(Date journeyDate) {
		this.journeyDate = journeyDate;
	}

}
