package com.portal.journey.entity;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedTimestamp;

import lombok.Data;

@Data
@DynamoDBTable(tableName = "passenger")
public class Passenger {

	/**
	 * id
	 */
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;

	/**
	 * firstName
	 */
	@DynamoDBAttribute
	private String firstName;

	/**
	 * lastName
	 */
	@DynamoDBAttribute
	private String lastName;

	/**
	 * mobileNo
	 */
	@DynamoDBAttribute
	private String mobileNo;

	/**
	 * address
	 */
	@DynamoDBAttribute
	private String address;

	/**
	 * createdDateTime
	 */
	@DynamoDBAttribute
	private Date createdDateTime;

	/**
	 * updatedDateTime
	 */
	@DynamoDBAttribute
	private Date updatedDateTime;

	/**
	 * createdBy
	 */
	@DynamoDBAttribute
	private String createdBy;

	/**
	 * updatedBy
	 */
	@DynamoDBAttribute
	private String updatedBy;

	public Passenger() {
		// TODO Auto-generated constructor stub
	}

	/**
	 * 
	 * @return
	 */
	public String getId() {
		return id;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * 
	 * @return
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * 
	 * @param firstName
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * 
	 * @return
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * 
	 * @param lastName
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * 
	 * @return
	 */
	public String getMobileNo() {
		return mobileNo;
	}

	/**
	 * 
	 * @param mobileNo
	 */
	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	/**
	 * 
	 * @return
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * 
	 * @param address
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * 
	 * @return
	 */
	public String getCreatedBy() {
		return createdBy;
	}

	/**
	 * 
	 * @param createdBy
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * 
	 * @return
	 */
	public String getUpdatedBy() {
		return updatedBy;
	}

	/**
	 * 
	 * @param updatedBy
	 */
	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	/**
	 * 
	 * @return
	 */
	@DynamoDBTypeConvertedTimestamp(pattern = "yyyyMMddHHmmssSSS", timeZone = "UTC")
	public Date getCreatedDateTime() {
		return createdDateTime;
	}

	/**
	 * 
	 * @param createdDateTime
	 */
	public void setCreatedDateTime(Date createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

	/**
	 * 
	 * @return
	 */
	@DynamoDBTypeConvertedTimestamp(pattern = "yyyyMMddHHmmssSSS", timeZone = "UTC")
	public Date getUpdatedDateTime() {
		return updatedDateTime;
	}

	/**
	 * 
	 * @param updatedDateTime
	 */
	public void setUpdatedDateTime(Date updatedDateTime) {
		this.updatedDateTime = updatedDateTime;
	}
}
